### ISSUE TITLE
Warnings during install

### ISSUE THREAD

**Issue by datawookie** [alexnakagawa/conversionr#4]
Hi,

Busy taking a look at your package. During the install process I get the following warnings:

```
Warning in Ops.factor(left, right) : ‘<’ not meaningful for factors
Warning in if (num < 0 | from == "" | to == "") stop("Invalid Input! Check documentation",  :
  the condition has length > 1 and only the first element will be used
Warning in Ops.factor(left, right) : ‘/’ not meaningful for factors
Warning in if (num < 0 | from == "" | to == "") { :
  the condition has length > 1 and only the first element will be used
Warning in if (num < 0 | from == "" | to == "") stop("Invalid Input! Check documentation",  :
  the condition has length > 1 and only the first element will be used
```

You really want to resolve this because your package should install without errors or warnings.

Please fix and let me know.

Thanks,
Andrew.

**Comment by alexnakagawa** [comment]
Hello,

Thank you so much for catching our error! Please see the most recent commit for a fixed copy with no more warning messages.

Cheers,

Alex

**Comment by datawookie** [comment]
Just checked this and I am happy that the issue is resolved. I think that you can close this now.
