### ISSUE TITLE
Usage examples in README

### ISSUE THREAD

**Issue by datawookie** [alexnakagawa/conversionr#5]
I think that it would be a good idea to provide usage examples in your README.

Look at README on https://github.com/tidyverse/ggplot2 for a good example.

**Comment by alexnakagawa** [comment]
Done! Let me know if there are any more issues.

Alex

**Comment by datawookie** [comment]
Great.

Two more things to sort out in this regard:

1. Include what the output should be for each of those commands (this gives potential users an idea of what to expect from the functions!); and
2. There's a problem with the "degree" character in the 100 Fahrenheit temperature.

**Comment by datawookie** [comment]
Any progress with this?

**Comment by datawookie** [comment]
Thanks!
